format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#090c0c fg:#a3aed2)\
$directory\
[](fg:#090c0c )\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#090c0c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = "   "
"Pictures" = "   "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#a3aed2)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#d6d6d6)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[character]
disabled = false
success_symbol = '[ 󰋇 ](bold fg:color_green)'
error_symbol = '[ 󰋇 ](bold fg:color_red)'
vimcmd_symbol = '[ 󰋇 ](bold fg:color_green)'
vimcmd_replace_one_symbol = '[ 󰋇 ](bold fg:color_purple)'
vimcmd_replace_symbol = '[ 󰋇 ](bold fg:color_purple)'
vimcmd_visual_symbol = '[ 󰋇 ](bold fg:color_yellow)'
